version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - dependency-cache-{{ checksum "package-lock.json" }}
                      - dependency-cache-

            - run: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: dependency-cache-{{ checksum "package-lock.json" }}

            - run: npm run verify:ci
            - persist_to_workspace:
                  root: "."
                  paths:
                      - lib
                      - package-lock.json
                      - test/*.js
                      - util

    javascript:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}

            - run: npm run src:tsc
            - run: npm run test:tsc
            - run: npm run test:end-to-end -- --language=JavaScript
