version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - dependency-cache-{{ checksum "package-lock.json" }}
                      - dependency-cache-

            - run: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: dependency-cache-{{ checksum "package-lock.json" }}

            - run: npm run ci:build
            - persist_to_workspace:
                  root: "."
                  paths:
                      - lib
                      - package-lock.json
                      - test/*.js
                      - test/unit
                      - util

    end-to-end/java:
        docker:
            - image: circleci/openjdk:latest-node-browsers

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}

            - run: npm run test:end-to-end -- --language=Java

    end-to-end/javascript:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}

            - run: npm run test:end-to-end -- --language=JavaScript

    end-to-end/python:
        docker:
            - image: circleci/python:3.6-node-browsers

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}

            - run: npm run test:end-to-end -- --language=Python

    end-to-end/ruby:
        docker:
            - image: circleci/ruby:2.5-node-browsers

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}

            - run: npm run test:end-to-end -- --language=Ruby

    end-to-end/typescript:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}

            - run: npm run test:end-to-end -- --language=TypeScript

    verify:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}

            - run: npm run verify:ci

workflows:
    version: 2
    build_and_end_to_end:
        jobs:
            - build
            - end-to-end/java:
                  requires:
                      - build
            - end-to-end/javascript:
                  requires:
                      - build
            - end-to-end/python:
                  requires:
                      - build
            - end-to-end/ruby:
                  requires:
                      - build
            - end-to-end/typescript:
                  requires:
                      - build
            - verify:
                  requires:
                      - build
